server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hot_video?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: admin123
  redis:
    host: localhost
    port: 6379
    timeout: 30000
    jedis:
      pool:
        min-idle: 0
        max-wait: -1
        max-active: 8
        max-idle: 8
  security:
    user:
      password: admin123
      name: root
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    #    发送邮箱
    username: 2334094446@qq.com
    #    授权码
    password: ktrxggtqfsxreadc
    #    端口号465或587
    port: 587
    #   配置ssl:加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml


# 阿里云oss配置
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tRYcqdhbYmhS1FhjMGy
    accessKeySecret: U9b75FNlGdWSw1Fc9GuuQrNXjAr93f
    bucketname: h-video
    urlPrefix:


