server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hot_video?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: admin123
  redis:
    host: localhost
    port: 6379
    timeout: 30000
    jedis:
      pool:
        min-idle: 0
        max-wait: -1
        max-active: 8
        max-idle: 8
  security:
    user:
      password: admin123
      name: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml





